name: My GitHub Actions Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t node-image .

      #   deploy:
      #     runs-on: ubuntu-latest
      #     needs: build

      #     steps:
      - name: Docker Tag
        run: |
          docker tag node-image brunofernandes95/node-image:latest
      - name: DockerHub Login
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Docker Push
        run: |
          docker push -a brunofernandes95/node-image
