name: My GitHub Actions Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t node-image .

    #   - name: Build
    #     run: |
    #       # Add your build commands here
    #     # Example:
    #       echo "Building my project..."

    #   - name: Deploy
    #     run: |
    #       # Add your deployment commands here
    #     # Example:
    #       echo "Deploying my project..."

    #       // docker build
    #       //docker push
