name: My GitHub Actions Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t node-image .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: DockerHub Login
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Docker Push
        run: |
          docker push

      # env:
      #     SUPER_SECRET: ${{ secrets.SuperSecret }}

    #   - name: Build
    #     run: |
    #       # Add your build commands here
    #     # Example:
    #       echo "Building my project..."

    #   - name: Deploy
    #     run: |
    #       # Add your deployment commands here
    #     # Example:
    #       echo "Deploying my project..."

    #       // docker build
    #       //docker push
